# Generated by Django 3.2.18 on 2023-03-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=20)),
                ('batch', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('re_password', models.CharField(max_length=30)),
                ('textarea', models.CharField(max_length=100)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('django', models.BooleanField()),
            ],
        ),
    ]
