# Generated by Django 3.2.18 on 2023-03-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='rollno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
